on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fancy.azurecr.io
        username: ${{ secrets.acr_fancy_username }}
        password: ${{ secrets.acr_fancy_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t fancy.azurecr.io/kluster:${{ github.sha }}
        docker push fancy.azurecr.io/kluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kluster69d2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kluster69d2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kluster69d2
        container-registry-url: fancy.azurecr.io
        container-registry-username: ${{ secrets.acr_fancy_username }}
        container-registry-password: ${{ secrets.acr_fancy_password }}
        secret-name: klusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kluster69d2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          fancy.azurecr.io/kluster:${{ github.sha }}
        imagepullsecrets: |
          klusterdockerauth